services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: transaction_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/transaction_service_db
      # Add any other environment variables your application needs, e.g., for API keys, webhook URLs, etc.
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
